spring.datasource.url=jdbc:postgresql://localhost:5432/bankflow
spring.datasource.username=richardlee
spring.datasource.password=

spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true

jwt.secret=${JWT_SECRET}